/**
 * Artwork Archive CSV column registry.
 * These are the fixed AA import template columns — we cannot change them.
 * Source: AA-Artist-Template.xlsx (40 cols) and AA-Artworks-Template.xlsx (68 cols)
 * Rebuilt 2026-03-18 from actual template files.
 */

export interface AAColumn {
  index: number
  name: string
  entityType: "artist" | "artwork"
}

export const AA_ARTIST_COLUMNS: AAColumn[] = [
  { index: 0, name: "First Name / Company Name", entityType: "artist" },
  { index: 1, name: "Last Name", entityType: "artist" },
  { index: 2, name: "Title", entityType: "artist" },
  { index: 3, name: "Nationality", entityType: "artist" },
  { index: 4, name: "Birth Date", entityType: "artist" },
  { index: 5, name: "Death Date", entityType: "artist" },
  { index: 6, name: "Email", entityType: "artist" },
  { index: 7, name: "Secondary Email", entityType: "artist" },
  { index: 8, name: "Phone", entityType: "artist" },
  { index: 9, name: "Mobile Phone", entityType: "artist" },
  { index: 10, name: "Work Phone", entityType: "artist" },
  { index: 11, name: "Primary Address 1", entityType: "artist" },
  { index: 12, name: "Address 2", entityType: "artist" },
  { index: 13, name: "City", entityType: "artist" },
  { index: 14, name: "State", entityType: "artist" },
  { index: 15, name: "Zip", entityType: "artist" },
  { index: 16, name: "Country", entityType: "artist" },
  { index: 17, name: "Secondary Address 1", entityType: "artist" },
  { index: 18, name: "Address 2", entityType: "artist" },
  { index: 19, name: "City", entityType: "artist" },
  { index: 20, name: "State", entityType: "artist" },
  { index: 21, name: "Zip", entityType: "artist" },
  { index: 22, name: "Country", entityType: "artist" },
  { index: 23, name: "Notes", entityType: "artist" },
  { index: 24, name: "Bio", entityType: "artist" },
  { index: 25, name: "Website", entityType: "artist" },
  { index: 26, name: "Company / Organization", entityType: "artist" },
  { index: 27, name: "Job Title", entityType: "artist" },
  { index: 28, name: "Artist", entityType: "artist" },
  { index: 29, name: "Appraiser", entityType: "artist" },
  { index: 30, name: "Groups", entityType: "artist" },
  { index: 31, name: "Spouse First Name", entityType: "artist" },
  { index: 32, name: "Spouse Last Name", entityType: "artist" },
  { index: 33, name: "Contact Tags", entityType: "artist" },
  { index: 34, name: "Contact Image Url", entityType: "artist" },
  { index: 35, name: "Instagram Url", entityType: "artist" },
  { index: 36, name: "Facebook Url", entityType: "artist" },
  { index: 37, name: "Twitter Url", entityType: "artist" },
  { index: 38, name: "LinkedIn Url", entityType: "artist" },
  { index: 39, name: "Pinterest URL", entityType: "artist" },
]

export const AA_ARTWORK_COLUMNS: AAColumn[] = [
  { index: 0, name: "Piece Name", entityType: "artwork" },
  { index: 1, name: "Artist First Name", entityType: "artwork" },
  { index: 2, name: "Artist Last Name", entityType: "artwork" },
  { index: 3, name: "Inventory Number", entityType: "artwork" },
  { index: 4, name: "Medium", entityType: "artwork" },
  { index: 5, name: "Type", entityType: "artwork" },
  { index: 6, name: "Status", entityType: "artwork" },
  { index: 7, name: "Height", entityType: "artwork" },
  { index: 8, name: "Width", entityType: "artwork" },
  { index: 9, name: "Depth", entityType: "artwork" },
  { index: 10, name: "Dimension Override", entityType: "artwork" },
  { index: 11, name: "Paper Height", entityType: "artwork" },
  { index: 12, name: "Paper Width", entityType: "artwork" },
  { index: 13, name: "Framed", entityType: "artwork" },
  { index: 14, name: "Framed Height", entityType: "artwork" },
  { index: 15, name: "Framed Width", entityType: "artwork" },
  { index: 16, name: "Framed Depth", entityType: "artwork" },
  { index: 17, name: "Subject Matter", entityType: "artwork" },
  { index: 18, name: "Price", entityType: "artwork" },
  { index: 19, name: "Fair Market Value", entityType: "artwork" },
  { index: 20, name: "Wholesale Value", entityType: "artwork" },
  { index: 21, name: "Insurance Value", entityType: "artwork" },
  { index: 22, name: "Creation Date", entityType: "artwork" },
  { index: 23, name: "Circa", entityType: "artwork" },
  { index: 24, name: "Creation date override", entityType: "artwork" },
  { index: 25, name: "Description", entityType: "artwork" },
  { index: 26, name: "Tags", entityType: "artwork" },
  { index: 27, name: "Notes", entityType: "artwork" },
  { index: 28, name: "Collections", entityType: "artwork" },
  { index: 29, name: "Current Location Name", entityType: "artwork" },
  { index: 30, name: "Current Location Start Date", entityType: "artwork" },
  { index: 31, name: "Current Location End Date", entityType: "artwork" },
  { index: 32, name: "Sub Location Name", entityType: "artwork" },
  { index: 33, name: "Tertiary Location Name", entityType: "artwork" },
  { index: 34, name: "Location Record Notes", entityType: "artwork" },
  { index: 35, name: "Location Record Longitude", entityType: "artwork" },
  { index: 36, name: "Location Record Latitude", entityType: "artwork" },
  { index: 37, name: "Sale/Donation/Gift", entityType: "artwork" },
  { index: 38, name: "Sale/Donation/Gift Date", entityType: "artwork" },
  { index: 39, name: "Sale/Donation/Gift Price", entityType: "artwork" },
  { index: 40, name: "Sale Discount", entityType: "artwork" },
  { index: 41, name: "Sale Commission", entityType: "artwork" },
  { index: 42, name: "First Name/Company Name of who you sold/donated/gifted to", entityType: "artwork" },
  { index: 43, name: "Last Name of who you sold/donated/gifted to", entityType: "artwork" },
  { index: 44, name: "Acquisition: Purchase Price", entityType: "artwork" },
  { index: 45, name: "Acquisition: Purchase Date", entityType: "artwork" },
  { index: 46, name: "Acquisition: Purchase Location", entityType: "artwork" },
  { index: 47, name: "Acquisition: Purchase from First Name/Company Name", entityType: "artwork" },
  { index: 48, name: "Acquisition: Purchase From Last Name", entityType: "artwork" },
  { index: 49, name: "Acquisition: Donation Date", entityType: "artwork" },
  { index: 50, name: "Acquisition: Donation Value", entityType: "artwork" },
  { index: 51, name: "Acquisition: Donor First Name/Company Name", entityType: "artwork" },
  { index: 52, name: "Acquisition: Donor Last", entityType: "artwork" },
  { index: 53, name: "Attribution Line", entityType: "artwork" },
  { index: 54, name: "Signed", entityType: "artwork" },
  { index: 55, name: "Signature Notes", entityType: "artwork" },
  { index: 56, name: "Edition", entityType: "artwork" },
  { index: 57, name: "Edition Info", entityType: "artwork" },
  { index: 58, name: "Appraisal Date", entityType: "artwork" },
  { index: 59, name: "Appraisal Price", entityType: "artwork" },
  { index: 60, name: "Appraiser First Name", entityType: "artwork" },
  { index: 61, name: "Appraiser Last Name", entityType: "artwork" },
  { index: 62, name: "Condition Status", entityType: "artwork" },
  { index: 63, name: "Condition Notes", entityType: "artwork" },
  { index: 64, name: "Weight", entityType: "artwork" },
  { index: 65, name: "Provenance Info", entityType: "artwork" },
  { index: 66, name: "Piece Image URLs", entityType: "artwork" },
  { index: 67, name: "Additional File URLs", entityType: "artwork" },
]

export const ALL_AA_COLUMNS = [...AA_ARTIST_COLUMNS, ...AA_ARTWORK_COLUMNS]
